# Generated by Django 3.2.3 on 2021-11-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0002_orderupdates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderupdates',
            options={'verbose_name_plural': 'Order Updates'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_status',
            field=models.CharField(choices=[('UNSUCCESSFUL', 'UNSUCCESSFUL'), ('PLACED', 'PLACED'), ('IN-TRANSIT', 'IN-TRANSIT'), ('AT DELIVERY CENTER', 'AT DELIVERY CENTER'), ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'), ('DELIVERED', 'DELIVERED')], default='UNSUCCESSFUL', max_length=50),
        ),
    ]
